version: '3.9'

services:
  fastapi-app:
    build: .
    container_name: fastapi-downloader
    ports:
      - "8000:8000"
    volumes:
      - ./downloads:/app/downloads
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
