version: '3.9'

services:
  fastapi-app:
    build: .
    container_name: fastapi-downloader
    ports:
      - "8000:8000"
    volumes:
      - ./downloads:/app/downloads
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    container_name: keycloak
    command:
      - start-dev
      - --import-realm
    environment:
      KC_DB: dev-mem
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
